# Ignore warnings not relevant to this specific project:
#
# 1) FindSecBugs identifies our use of ThreadLocalRandom as predictable.
# However, the aim of this library is to provide implementation of ZigguratGaussian
# that supports use of any of Java's current random number generators, including
# ThreadLocalRandom. Of course, if randomness is used within a security context, 
# the SecureRandom class should instead be used.  But this is not the case here.

ignore = ["PREDICTABLE_RANDOM"]

# Ignore results from these directories

ignoreFiles = """
tests/
"""

jdk11 = true
