name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Build with Maven
      run: mvn -B test -Pcoverage

    - name: Generate Jacoco Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@development

    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"

    - name: Commit and push jacoco badge
      if: ${{ github.event_name == 'push' }}
      run: |
        if [ $(git status | grep -c "github/badges") != "0" ]; then
          echo "Badge File Changed"
          git config --global user.name 'Vincent A Cicirello'
          git config --global user.email 'cicirello@users.noreply.github.com'
          git add ./\*.svg
          git commit -m "Jacoco Coverage Badge Update"
          git push
        else
          echo "Badge File Not Changed"
        fi

    - name: Upload Jacoco coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/
