name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Build with Maven
      run: mvn -B test -Pcoverage

    - name: Generate Jacoco Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@development

    - name: Inspect results
      run: |
        echo "Badge"
        cat .github/badges/jacoco.svg
        echo " "
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"

